### ISSUE TITLE
Small images - Google Play Music

### ISSUE THREAD

**Issue by kayericson** [svbnet/AthamePlugin.GooglePlayMusic#7]
so image from GPM have 512 px, but it's possible to download/tag in higher quality
standart picture link (webm): https://lh3.googleusercontent.com/dkdllcTKsMezuJFFsdV36sOhEcjL4GV9mllrPADBMCGJv-AK9gvKYaQCYw8lxNZ0aGPkkbbhAw=s512-c-e100-rwu-v1
jpg 1400px in this case with 100% JPEG quality [may be in any resolution]: 
https://lh3.googleusercontent.com/dkdllcTKsMezuJFFsdV36sOhEcjL4GV9mllrPADBMCGJv-AK9gvKYaQCYw8lxNZ0aGPkkbbhAw=s1400-c-e100

**Comment by greenzwiz** [comment]
I was looking at this as well, this would be a great implementation.

**Comment by svbnet** [comment]
99% sure that the tagging library I'm using doesn't support WEBP, so this will probably not be implemented for now, unfortunately.

**Comment by kayericson** [comment]
But you can change webp to jpeg simply remove at the end of the link "-rwu-v1"
Take a closer look at the links that I sent; second is JPEG
